<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Mon CRUD MVC</title>
</head>
<body>
    <nav>
        <a href="index.php?route=show_user">show user</a> |
        <a href="index.php?route=create_user">create user</a> |
        <a href="index.php?route=update_user">update user</a> |
    </nav>
    <hr>
    <?php require 'templates/users/' . $route . '.phtml'; ?>

</body>
</html>
